### ISSUE TITLE
React Hot Reload not working on Docker For Windows

### ISSUE THREAD

**Issue by SC7639** [Atyantik/react-pwa#42]
I've been looking into getting hot reload to work on docker for windows. I've found out that I need to get webpack to poll files due to the filesystem used in docker for windows mounted volumes, I need to add the below to the webpack configuration but I'm not sure where to add it in the dev.babel.js file (if that is the correct file). I've tried adding it in multiple places but I'm not sure if it's not working or I don't have the configuration correct.
```
watchOptions: {
    poll: 1000
}
```
Any help will be greatly appreciated

**Comment by tirthbodawala** [comment]
@SC7639 Let me have a look at it. I have tested docker on Linux and was working fine. it is supposed to work for Windows as well but let me go through it.

**Comment by tirthbodawala** [comment]
@SC7639 Can you please share your windows details along with the version of docker you are using?

**Comment by SC7639** [comment]
I'm using Windows 10 with docker for windows. I've had this issue before with things like nodemon. It's because HyperV doesn't propagate file system events so I know the fix is polling for file changes.
Output of `docker version`:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by tirthbodawala** [comment]
@SC7639 I have updated the code to accept watchOptions from config to enable watch config,
Please update the file webpack/dev.babel.js
by the following option in devServer section:
```
const commonClientConfig = {
  // ... other config
  devServer: {
    // .. other dev server config 
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
  },
};
```
This should also be updated for service worker configuration just in case, ( I added backup config from above but adding it to service worker would make more sense:

```
const serviceWorkerConfig = {
  // ... other config
  devServer: {
    // .. other dev server config 
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
  },
};
```

Let me know if this fixes the issue!

**Comment by tirthbodawala** [comment]
@SC7639 Were you able to configure it after this update?

**Comment by tirthbodawala** [comment]
Closing due to no-response

**Comment by SC7639** [comment]
I've tried after updating the configuration and it's still not hot reloading. I've also noticed that the nodemon doesn't reload either if any of the files are changed that it's watching.

**Comment by tirthbodawala** [comment]
Ok. I shall debug this in detail, but I have applied the patch suggested. Is there anything we are missing?

**Comment by SC7639** [comment]
Sorry I was wrong about it fixing the issue. I cloned a fresh version of the repo and it works. Sorry for the mix up

**Comment by hugominas** [comment]
you need to add host: '0.0.0.0' for hot reloading to work in a docker container:

```  webpackConfig.devServer = {
    hot: true,
    port: port,
    progress: true,
    host: '0.0.0.0',
   .... ```

**Comment by aaaleeex7** [comment]
Hey i have the same issue with a react project on windows with docker/docker-compose. My whole node_modules foulder is mounted into the virtual machine so i dont have access to the node_modules folder to edit the dev.babel.js file for hot-reloading. Is there any possible soulution?

**Comment by tirthbodawala** [comment]
@aaaleeex7  which version of ReactPWA are you using?

**Comment by aaaleeex7** [comment]
@tirthbodawala create-react-app is v2.1.1
